export interface CarSpecifications {
  engine?: string
  battery?: string
  range?: string
  displacement?: string
  maxPower?: string
  maxTorque?: string
  fuelTankCapacity?: string
  chargingTime?: string
  bootSpace?: string
  seatingCapacity?: number
  groundClearance?: string
  length?: string
  width?: string
  height?: string
  wheelbase?: string
  kerbWeight?: string
  gearbox?: string
  driveType?: string
  suspensionFront?: string
  suspensionRear?: string
  brakeFront?: string
  brakeRear?: string
  wheelSize?: string
  tyreSize?: string
}

export interface CarSafety {
  airbags?: string
  abs?: boolean
  ebd?: boolean
  esp?: boolean
  hillAssist?: boolean
  tractionControl?: boolean
  isofix?: boolean
  reverseCamera?: boolean
  parkingSensors?: string
  ncapRating?: string
}

export interface CarFeatures {
  airConditioning?: string
  powerSteering?: boolean
  powerWindows?: string
  centralLocking?: boolean
  keylessEntry?: boolean
  pushButtonStart?: boolean
  cruiseControl?: boolean
  musicSystem?: string
  bluetooth?: boolean
  usb?: boolean
  aux?: boolean
  steeringMountedControls?: boolean
  touchscreenSize?: string
  navigation?: boolean
  androidAuto?: boolean
  appleCarPlay?: boolean
  wirelessCharging?: boolean
  sunroof?: string
  alloyWheels?: boolean
  fogLamps?: boolean
  drl?: boolean
  ledHeadlights?: boolean
  ledTaillights?: boolean
  electricOrvm?: boolean
  rainSensingWipers?: boolean
  rearWiper?: boolean
  rearDefogger?: boolean
}

export interface CarVariant {
  name: string
  price: number
  fuelType: string
  transmission: string
  mileage: string
  available: boolean
}

export interface CarData {
  id: number
  name: string
  brand: string
  model: string
  slug: string
  launchYear: number
  bodyType: string
  priceRange: { min: number; max: number }
  priceDisplay: string
  image: string
  images: string[]
  rating: number
  reviews: number
  overview: string
  keyHighlights: string[]
  specifications: CarSpecifications
  safety: CarSafety
  features: CarFeatures
  variants: CarVariant[] // ALWAYS REQUIRED
  competitors: number[]
  keywords: string[]
  isPopular: boolean
  isUpcoming: boolean
  isElectric: boolean
  segment: string
}



export const carsDatabase: CarData[] = [
  // MARUTI SUZUKI CARS
  {
    id: 1,
    name: "Maruti Suzuki Swift",
    brand: "Maruti Suzuki",
    model: "Swift",
    slug: "maruti-suzuki-swift",
    launchYear: 2018,
    bodyType: "Hatchback",
    priceRange: { min: 5.85, max: 8.67 },
    priceDisplay: "₹5.85 - 8.67 Lakh",
    image: "/placeholder.svg?height=200&width=300",
    images: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    rating: 4.2,
    reviews: 1250,
    overview:
      "The Maruti Suzuki Swift is one of India's most popular hatchbacks, known for its sporty design, fuel efficiency, and reliable performance. It offers a perfect blend of style and practicality.",
    keyHighlights: [
      "Best-in-class fuel efficiency",
      "Sporty and stylish design",
      "Reliable Maruti service network",
      "Affordable maintenance",
      "Good resale value",
    ],
    specifications: {
      engine: "1.2L K-Series Petrol",
      displacement: "1197 cc",
      maxPower: "89 PS @ 6000 rpm",
      maxTorque: "113 Nm @ 4200 rpm",
      fuelTankCapacity: "37 L",
      bootSpace: "268 L",
      seatingCapacity: 5,
      groundClearance: "163 mm",
      length: "3845 mm",
      width: "1735 mm",
      height: "1530 mm",
      wheelbase: "2450 mm",
      kerbWeight: "860 kg",
      gearbox: "5-speed Manual / AMT",
      driveType: "FWD",
      suspensionFront: "MacPherson Strut",
      suspensionRear: "Torsion Beam",
      brakeFront: "Disc",
      brakeRear: "Drum",
      wheelSize: "15 inch",
      tyreSize: "185/65 R15",
    },
    safety: {
      airbags: "2 Airbags",
      abs: true,
      ebd: true,
      esp: false,
      hillAssist: false,
      tractionControl: false,
      isofix: true,
      reverseCamera: false,
      parkingSensors: "Rear",
      ncapRating: "2 Star",
    },
    features: {
      airConditioning: "Manual AC",
      powerSteering: true,
      powerWindows: "Front & Rear",
      centralLocking: true,
      keylessEntry: true,
      pushButtonStart: true,
      cruiseControl: false,
      musicSystem: "SmartPlay Studio",
      bluetooth: true,
      usb: true,
      aux: true,
      steeringMountedControls: true,
      touchscreenSize: "7 inch",
      navigation: false,
      androidAuto: true,
      appleCarPlay: true,
      wirelessCharging: false,
      alloyWheels: true,
      fogLamps: true,
      drl: false,
      ledHeadlights: false,
      ledTaillights: false,
      electricOrvm: true,
      rainSensingWipers: false,
      rearWiper: true,
      rearDefogger: true,
    },
    variants: [
      { name: "LXI", price: 5.85, fuelType: "Petrol", transmission: "Manual", mileage: "23.2 kmpl", available: true },
      { name: "VXI", price: 6.45, fuelType: "Petrol", transmission: "Manual", mileage: "23.2 kmpl", available: true },
      { name: "VXI AMT", price: 6.95, fuelType: "Petrol", transmission: "AMT", mileage: "23.76 kmpl", available: true },
      { name: "ZXI", price: 7.25, fuelType: "Petrol", transmission: "Manual", mileage: "23.2 kmpl", available: true },
      { name: "ZXI AMT", price: 7.75, fuelType: "Petrol", transmission: "AMT", mileage: "23.76 kmpl", available: true },
    ],
    competitors: [2, 7, 14],
    keywords: ["swift", "maruti", "suzuki", "hatchback", "petrol", "manual", "amt", "fuel efficient"],
    isPopular: true,
    isUpcoming: false,
    isElectric: false,
    segment: "B1-Hatchback",
  },
  {
    id: 2,
    name: "Maruti Suzuki Baleno",
    brand: "Maruti Suzuki",
    model: "Baleno",
    slug: "maruti-suzuki-baleno",
    launchYear: 2015,
    bodyType: "Hatchback",
    priceRange: { min: 6.35, max: 9.69 },
    priceDisplay: "₹6.35 - 9.69 Lakh",
    image: "/placeholder.svg?height=200&width=300",
    images: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    rating: 4.1,
    reviews: 1100,
    overview:
      "The Maruti Suzuki Baleno is a premium hatchback that offers a spacious cabin, advanced features, and excellent fuel efficiency. It's positioned as a premium offering in the hatchback segment.",
    keyHighlights: [
      "Spacious and premium interior",
      "Advanced SmartPlay infotainment",
      "Excellent fuel efficiency",
      "Premium build quality",
      "Strong resale value",
    ],
    specifications: {
      engine: "1.2L K-Series Petrol",
      displacement: "1197 cc",
      maxPower: "89 PS @ 6000 rpm",
      maxTorque: "113 Nm @ 4200 rpm",
      fuelTankCapacity: "37 L",
      bootSpace: "339 L",
      seatingCapacity: 5,
      groundClearance: "170 mm",
      length: "3990 mm",
      width: "1745 mm",
      height: "1500 mm",
      wheelbase: "2520 mm",
      kerbWeight: "865 kg",
      gearbox: "5-speed Manual / CVT",
      driveType: "FWD",
      suspensionFront: "MacPherson Strut",
      suspensionRear: "Torsion Beam",
      brakeFront: "Disc",
      brakeRear: "Drum",
      wheelSize: "16 inch",
      tyreSize: "195/55 R16",
    },
    safety: {
      airbags: "2 Airbags",
      abs: true,
      ebd: true,
      esp: false,
      hillAssist: false,
      tractionControl: false,
      isofix: true,
      reverseCamera: true,
      parkingSensors: "Rear",
      ncapRating: "4 Star",
    },
    features: {
      airConditioning: "Automatic Climate Control",
      powerSteering: true,
      powerWindows: "Front & Rear",
      centralLocking: true,
      keylessEntry: true,
      pushButtonStart: true,
      cruiseControl: false,
      musicSystem: "SmartPlay Pro",
      bluetooth: true,
      usb: true,
      aux: true,
      steeringMountedControls: true,
      touchscreenSize: "9 inch",
      navigation: true,
      androidAuto: true,
      appleCarPlay: true,
      wirelessCharging: false,
      sunroof: "Not Available",
      alloyWheels: true,
      fogLamps: true,
      drl: true,
      ledHeadlights: true,
      ledTaillights: true,
      electricOrvm: true,
      rainSensingWipers: false,
      rearWiper: true,
      rearDefogger: true,
    },
    variants: [
      {
        name: "Sigma",
        price: 6.35,
        fuelType: "Petrol",
        transmission: "Manual",
        mileage: "22.35 kmpl",
        available: true,
      },
      {
        name: "Delta",
        price: 7.25,
        fuelType: "Petrol",
        transmission: "Manual",
        mileage: "22.35 kmpl",
        available: true,
      },
      { name: "Zeta", price: 8.15, fuelType: "Petrol", transmission: "Manual", mileage: "22.35 kmpl", available: true },
      {
        name: "Alpha",
        price: 9.25,
        fuelType: "Petrol",
        transmission: "Manual",
        mileage: "22.35 kmpl",
        available: true,
      },
      {
        name: "Alpha CVT",
        price: 9.69,
        fuelType: "Petrol",
        transmission: "CVT",
        mileage: "21.01 kmpl",
        available: true,
      },
    ],
    competitors: [1, 7, 14],
    keywords: ["baleno", "maruti", "suzuki", "premium hatchback", "petrol", "cvt", "spacious"],
    isPopular: true,
    isUpcoming: false,
    isElectric: false,
    segment: "B2-Hatchback",
  },
  {
    id: 3,
    name: "Maruti Suzuki Dzire",
    brand: "Maruti Suzuki",
    model: "Dzire",
    slug: "maruti-suzuki-dzire",
    launchYear: 2017,
    bodyType: "Sedan",
    priceRange: { min: 6.57, max: 9.39 },
    priceDisplay: "₹6.57 - 9.39 Lakh",
    image: "/placeholder.svg?height=200&width=300",
    images: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    rating: 4.3,
    reviews: 1400,
    overview:
      "The Maruti Suzuki Dzire is India's best-selling compact sedan, offering excellent fuel efficiency, spacious interiors, and reliable performance. It's the perfect family car for Indian conditions.",
    keyHighlights: [
      "India's best-selling sedan",
      "Excellent fuel efficiency",
      "Spacious cabin and boot",
      "Reliable and low maintenance",
      "Strong resale value",
    ],
    specifications: {
      engine: "1.2L K-Series Petrol",
      displacement: "1197 cc",
      maxPower: "89 PS @ 6000 rpm",
      maxTorque: "113 Nm @ 4200 rpm",
      fuelTankCapacity: "37 L",
      bootSpace: "378 L",
      seatingCapacity: 5,
      groundClearance: "163 mm",
      length: "3995 mm",
      width: "1735 mm",
      height: "1515 mm",
      wheelbase: "2450 mm",
      kerbWeight: "905 kg",
      gearbox: "5-speed Manual / AMT",
      driveType: "FWD",
      suspensionFront: "MacPherson Strut",
      suspensionRear: "Torsion Beam",
      brakeFront: "Disc",
      brakeRear: "Drum",
      wheelSize: "15 inch",
      tyreSize: "185/65 R15",
    },
    safety: {
      airbags: "2 Airbags",
      abs: true,
      ebd: true,
      esp: false,
      hillAssist: false,
      tractionControl: false,
      isofix: true,
      reverseCamera: false,
      parkingSensors: "Rear",
      ncapRating: "2 Star",
    },
    features: {
      airConditioning: "Manual AC",
      powerSteering: true,
      powerWindows: "Front & Rear",
      centralLocking: true,
      keylessEntry: true,
      pushButtonStart: true,
      cruiseControl: false,
      musicSystem: "SmartPlay Studio",
      bluetooth: true,
      usb: true,
      aux: true,
      steeringMountedControls: true,
      touchscreenSize: "7 inch",
      navigation: false,
      androidAuto: true,
      appleCarPlay: true,
      wirelessCharging: false,
      alloyWheels: true,
      fogLamps: true,
      drl: false,
      ledHeadlights: false,
      ledTaillights: false,
      electricOrvm: true,
      rainSensingWipers: false,
      rearWiper: false,
      rearDefogger: true,
    },
    variants: [
      { name: "LXI", price: 6.57, fuelType: "Petrol", transmission: "Manual", mileage: "24.12 kmpl", available: true },
      { name: "VXI", price: 7.17, fuelType: "Petrol", transmission: "Manual", mileage: "24.12 kmpl", available: true },
      { name: "VXI AMT", price: 7.67, fuelType: "Petrol", transmission: "AMT", mileage: "24.12 kmpl", available: true },
      { name: "ZXI", price: 8.17, fuelType: "Petrol", transmission: "Manual", mileage: "24.12 kmpl", available: true },
      { name: "ZXI AMT", price: 8.67, fuelType: "Petrol", transmission: "AMT", mileage: "24.12 kmpl", available: true },
    ],
    competitors: [4, 12],
    keywords: ["dzire", "maruti", "suzuki", "sedan", "compact sedan", "petrol", "amt", "family car"],
    isPopular: true,
    isUpcoming: false,
    isElectric: false,
    segment: "B-Sedan",
  },

  // HYUNDAI CARS
  {
    id: 4,
    name: "Hyundai Creta",
    brand: "Hyundai",
    model: "Creta",
    slug: "hyundai-creta",
    launchYear: 2020,
    bodyType: "SUV",
    priceRange: { min: 10.87, max: 18.73 },
    priceDisplay: "₹10.87 - 18.73 Lakh",
    image: "/placeholder.svg?height=200&width=300",
    images: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    rating: 4.4,
    reviews: 890,
    overview:
      "The Hyundai Creta is one of India's most popular compact SUVs, offering a perfect blend of style, features, and performance. It leads the segment with its premium design and advanced technology.",
    keyHighlights: [
      "Segment-leading features",
      "Premium design and build quality",
      "Multiple engine and transmission options",
      "Excellent ride and handling",
      "Strong brand reliability",
    ],
    specifications: {
      engine: "1.5L Petrol / 1.5L Diesel / 1.4L Turbo Petrol",
      displacement: "1497 cc / 1493 cc / 1353 cc",
      maxPower: "115 PS / 115 PS / 140 PS",
      maxTorque: "144 Nm / 250 Nm / 242 Nm",
      fuelTankCapacity: "50 L",
      bootSpace: "433 L",
      seatingCapacity: 5,
      groundClearance: "190 mm",
      length: "4300 mm",
      width: "1790 mm",
      height: "1635 mm",
      wheelbase: "2610 mm",
      kerbWeight: "1245 kg",
      gearbox: "6-speed Manual / CVT / DCT / Automatic",
      driveType: "FWD",
      suspensionFront: "MacPherson Strut",
      suspensionRear: "Coupled Torsion Beam Axle",
      brakeFront: "Disc",
      brakeRear: "Disc",
      wheelSize: "17 inch",
      tyreSize: "215/60 R17",
    },
    safety: {
      airbags: "6 Airbags",
      abs: true,
      ebd: true,
      esp: true,
      hillAssist: true,
      tractionControl: true,
      isofix: true,
      reverseCamera: true,
      parkingSensors: "Front & Rear",
      ncapRating: "5 Star",
    },
    features: {
      airConditioning: "Automatic Climate Control",
      powerSteering: true,
      powerWindows: "Front & Rear",
      centralLocking: true,
      keylessEntry: true,
      pushButtonStart: true,
      cruiseControl: true,
      musicSystem: "BlueLink Connected Car",
      bluetooth: true,
      usb: true,
      aux: true,
      steeringMountedControls: true,
      touchscreenSize: "10.25 inch",
      navigation: true,
      androidAuto: true,
      appleCarPlay: true,
      wirelessCharging: true,
      sunroof: "Electric Sunroof",
      alloyWheels: true,
      fogLamps: true,
      drl: true,
      ledHeadlights: true,
      ledTaillights: true,
      electricOrvm: true,
      rainSensingWipers: true,
      rearWiper: true,
      rearDefogger: true,
    },
    variants: [
      { name: "E", price: 10.87, fuelType: "Petrol", transmission: "Manual", mileage: "17.4 kmpl", available: true },
      { name: "EX", price: 12.18, fuelType: "Petrol", transmission: "Manual", mileage: "17.4 kmpl", available: true },
      { name: "S", price: 13.18, fuelType: "Petrol", transmission: "Manual", mileage: "17.4 kmpl", available: true },
      { name: "SX", price: 15.29, fuelType: "Petrol", transmission: "CVT", mileage: "16.8 kmpl", available: true },
      { name: "SX(O)", price: 17.73, fuelType: "Petrol", transmission: "CVT", mileage: "16.8 kmpl", available: true },
      {
        name: "SX Turbo",
        price: 18.73,
        fuelType: "Petrol",
        transmission: "DCT",
        mileage: "16.8 kmpl",
        available: true,
      },
    ],
    competitors: [9, 15, 3],
    keywords: ["creta", "hyundai", "suv", "compact suv", "petrol", "diesel", "turbo", "automatic", "sunroof"],
    isPopular: true,
    isUpcoming: false,
    isElectric: false,
    segment: "Compact SUV",
  },
  {
    id: 5,
    name: "Hyundai i20",
    brand: "Hyundai",
    model: "i20",
    slug: "hyundai-i20",
    launchYear: 2020,
    bodyType: "Hatchback",
    priceRange: { min: 7.04, max: 11.21 },
    priceDisplay: "₹7.04 - 11.21 Lakh",
    image: "/placeholder.svg?height=200&width=300",
    images: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    rating: 4.0,
    reviews: 980,
    overview:
      "The Hyundai i20 is a premium hatchback that offers sporty design, advanced features, and multiple engine options. It's positioned as a feature-rich alternative in the premium hatchback segment.",
    keyHighlights: [
      "Sporty and premium design",
      "Feature-rich cabin",
      "Multiple engine options",
      "Good build quality",
      "Advanced safety features",
    ],
    specifications: {
      engine: "1.2L Petrol / 1.0L Turbo Petrol / 1.5L Diesel",
      displacement: "1197 cc / 998 cc / 1493 cc",
      maxPower: "83 PS / 120 PS / 100 PS",
      maxTorque: "113 Nm / 172 Nm / 240 Nm",
      fuelTankCapacity: "37 L",
      bootSpace: "311 L",
      seatingCapacity: 5,
      groundClearance: "165 mm",
      length: "3995 mm",
      width: "1775 mm",
      height: "1505 mm",
      wheelbase: "2580 mm",
      kerbWeight: "1040 kg",
      gearbox: "5-speed Manual / CVT / 6-speed Manual",
      driveType: "FWD",
      suspensionFront: "MacPherson Strut",
      suspensionRear: "Coupled Torsion Beam Axle",
      brakeFront: "Disc",
      brakeRear: "Drum",
      wheelSize: "16 inch",
      tyreSize: "195/55 R16",
    },
    safety: {
      airbags: "6 Airbags",
      abs: true,
      ebd: true,
      esp: true,
      hillAssist: true,
      tractionControl: true,
      isofix: true,
      reverseCamera: true,
      parkingSensors: "Rear",
      ncapRating: "3 Star",
    },
    features: {
      airConditioning: "Automatic Climate Control",
      powerSteering: true,
      powerWindows: "Front & Rear",
      centralLocking: true,
      keylessEntry: true,
      pushButtonStart: true,
      cruiseControl: false,
      musicSystem: "BlueLink Connected Car",
      bluetooth: true,
      usb: true,
      aux: true,
      steeringMountedControls: true,
      touchscreenSize: "10.25 inch",
      navigation: true,
      androidAuto: true,
      appleCarPlay: true,
      wirelessCharging: true,
      sunroof: "Electric Sunroof",
      alloyWheels: true,
      fogLamps: true,
      drl: true,
      ledHeadlights: true,
      ledTaillights: true,
      electricOrvm: true,
      rainSensingWipers: false,
      rearWiper: true,
      rearDefogger: true,
    },
    variants: [
      {
        name: "Magna",
        price: 7.04,
        fuelType: "Petrol",
        transmission: "Manual",
        mileage: "20.35 kmpl",
        available: true,
      },
      {
        name: "Sportz",
        price: 8.24,
        fuelType: "Petrol",
        transmission: "Manual",
        mileage: "20.35 kmpl",
        available: true,
      },
      { name: "Asta", price: 9.99, fuelType: "Petrol", transmission: "CVT", mileage: "19.65 kmpl", available: true },
      {
        name: "Asta(O)",
        price: 11.21,
        fuelType: "Petrol",
        transmission: "CVT",
        mileage: "19.65 kmpl",
        available: true,
      },
    ],
    competitors: [1, 2, 14],
    keywords: ["i20", "hyundai", "premium hatchback", "petrol", "turbo", "diesel", "sunroof", "features"],
    isPopular: true,
    isUpcoming: false,
    isElectric: false,
    segment: "B2-Hatchback",
  },
  {
    id: 6,
    name: "Hyundai Venue",
    brand: "Hyundai",
    model: "Venue",
    slug: "hyundai-venue",
    launchYear: 2019,
    bodyType: "SUV",
    priceRange: { min: 7.94, max: 12.72 },
    priceDisplay: "₹7.94 - 12.72 Lakh",
    image: "/placeholder.svg?height=200&width=300",
    images: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    rating: 4.2,
    reviews: 650,
    overview:
      "The Hyundai Venue is a compact SUV that offers a feature-rich experience with connected car technology. It's designed for urban driving with a bold design and advanced features.",
    keyHighlights: [
      "Connected car technology",
      "Compact and urban-friendly",
      "Feature-rich interior",
      "Multiple engine options",
      "Good fuel efficiency",
    ],
    specifications: {
      engine: "1.2L Petrol / 1.0L Turbo Petrol / 1.5L Diesel",
      displacement: "1197 cc / 998 cc / 1493 cc",
      maxPower: "83 PS / 120 PS / 100 PS",
      maxTorque: "113 Nm / 172 Nm / 240 Nm",
      fuelTankCapacity: "45 L",
      bootSpace: "350 L",
      seatingCapacity: 5,
      groundClearance: "195 mm",
      length: "3995 mm",
      width: "1770 mm",
      height: "1617 mm",
      wheelbase: "2500 mm",
      kerbWeight: "1185 kg",
      gearbox: "5-speed Manual / CVT / 6-speed Manual",
      driveType: "FWD",
      suspensionFront: "MacPherson Strut",
      suspensionRear: "Coupled Torsion Beam Axle",
      brakeFront: "Disc",
      brakeRear: "Drum",
      wheelSize: "16 inch",
      tyreSize: "195/60 R16",
    },
    safety: {
      airbags: "6 Airbags",
      abs: true,
      ebd: true,
      esp: true,
      hillAssist: true,
      tractionControl: true,
      isofix: true,
      reverseCamera: true,
      parkingSensors: "Rear",
      ncapRating: "3 Star",
    },
    features: {
      airConditioning: "Automatic Climate Control",
      powerSteering: true,
      powerWindows: "Front & Rear",
      centralLocking: true,
      keylessEntry: true,
      pushButtonStart: true,
      cruiseControl: false,
      musicSystem: "BlueLink Connected Car",
      bluetooth: true,
      usb: true,
      aux: true,
      steeringMountedControls: true,
      touchscreenSize: "8 inch",
      navigation: true,
      androidAuto: true,
      appleCarPlay: true,
      wirelessCharging: true,
      sunroof: "Electric Sunroof",
      alloyWheels: true,
      fogLamps: true,
      drl: true,
      ledHeadlights: true,
      ledTaillights: true,
      electricOrvm: true,
      rainSensingWipers: false,
      rearWiper: true,
      rearDefogger: true,
    },
    variants: [
      { name: "E", price: 7.94, fuelType: "Petrol", transmission: "Manual", mileage: "18.15 kmpl", available: true },
      { name: "S", price: 9.09, fuelType: "Petrol", transmission: "Manual", mileage: "18.15 kmpl", available: true },
      { name: "SX", price: 10.89, fuelType: "Petrol", transmission: "CVT", mileage: "18.27 kmpl", available: true },
      { name: "SX(O)", price: 12.72, fuelType: "Petrol", transmission: "CVT", mileage: "18.27 kmpl", available: true },
    ],
    competitors: [19, 3, 15],
    keywords: ["venue", "hyundai", "compact suv", "petrol", "turbo", "diesel", "connected car", "urban"],
    isPopular: true,
    isUpcoming: false,
    isElectric: false,
    segment: "Sub-Compact SUV",
  },

  // TATA CARS
  {
    id: 7,
    name: "Tata Nexon",
    brand: "Tata",
    model: "Nexon",
    slug: "tata-nexon",
    launchYear: 2017,
    bodyType: "SUV",
    priceRange: { min: 7.6, max: 14.08 },
    priceDisplay: "₹7.60 - 14.08 Lakh",
    image: "/placeholder.svg?height=200&width=300",
    images: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    rating: 4.1,
    reviews: 2100,
    overview:
      "The Tata Nexon is India's first 5-star safety rated compact SUV. It offers a perfect blend of safety, style, and performance with both petrol and electric variants available.",
    keyHighlights: [
      "5-star Global NCAP safety rating",
      "Stylish and bold design",
      "Available in EV variant",
      "Good build quality",
      "Competitive pricing",
    ],
    specifications: {
      engine: "1.2L Turbo Petrol / 1.5L Diesel",
      displacement: "1199 cc / 1497 cc",
      maxPower: "120 PS / 110 PS",
      maxTorque: "170 Nm / 260 Nm",
      fuelTankCapacity: "44 L",
      bootSpace: "350 L",
      seatingCapacity: 5,
      groundClearance: "209 mm",
      length: "3993 mm",
      width: "1811 mm",
      height: "1606 mm",
      wheelbase: "2498 mm",
      kerbWeight: "1180 kg",
      gearbox: "6-speed Manual / AMT",
      driveType: "FWD",
      suspensionFront: "MacPherson Strut",
      suspensionRear: "Twist Beam",
      brakeFront: "Disc",
      brakeRear: "Drum",
      wheelSize: "16 inch",
      tyreSize: "215/60 R16",
    },
    safety: {
      airbags: "2 Airbags",
      abs: true,
      ebd: true,
      esp: true,
      hillAssist: true,
      tractionControl: true,
      isofix: true,
      reverseCamera: true,
      parkingSensors: "Rear",
      ncapRating: "5 Star",
    },
    features: {
      airConditioning: "Automatic Climate Control",
      powerSteering: true,
      powerWindows: "Front & Rear",
      centralLocking: true,
      keylessEntry: true,
      pushButtonStart: true,
      cruiseControl: false,
      musicSystem: "Harman ConnectNext",
      bluetooth: true,
      usb: true,
      aux: true,
      steeringMountedControls: true,
      touchscreenSize: "7 inch",
      navigation: false,
      androidAuto: true,
      appleCarPlay: true,
      wirelessCharging: false,
      alloyWheels: true,
      fogLamps: true,
      drl: true,
      ledHeadlights: false,
      ledTaillights: true,
      electricOrvm: true,
      rainSensingWipers: false,
      rearWiper: true,
      rearDefogger: true,
    },
    variants: [
      { name: "XE", price: 7.6, fuelType: "Petrol", transmission: "Manual", mileage: "17.57 kmpl", available: true },
      { name: "XM", price: 8.9, fuelType: "Petrol", transmission: "Manual", mileage: "17.57 kmpl", available: true },
      { name: "XT", price: 10.4, fuelType: "Petrol", transmission: "Manual", mileage: "17.57 kmpl", available: true },
      { name: "XZ+", price: 12.8, fuelType: "Petrol", transmission: "AMT", mileage: "17.05 kmpl", available: true },
      {
        name: "XZ+ (S)",
        price: 14.08,
        fuelType: "Petrol",
        transmission: "AMT",
        mileage: "17.05 kmpl",
        available: true,
      },
    ],
    competitors: [4, 6, 19],
    keywords: ["nexon", "tata", "compact suv", "petrol", "diesel", "5 star safety", "ev available"],
    isPopular: true,
    isUpcoming: false,
    isElectric: false,
    segment: "Compact SUV",
  },
  {
    id: 8,
    name: "Tata Harrier",
    brand: "Tata",
    model: "Harrier",
    slug: "tata-harrier",
    launchYear: 2019,
    bodyType: "SUV",
    priceRange: { min: 14.69, max: 22.69 },
    priceDisplay: "₹14.69 - 22.69 Lakh",
    image: "/placeholder.svg?height=200&width=300",
    images: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    rating: 4.2,
    reviews: 560,
    overview:
      "The Tata Harrier is a premium SUV that offers commanding road presence, spacious interiors, and advanced features. Built on the OMEGA platform, it delivers a premium driving experience.",
    keyHighlights: [
      "Premium and imposing design",
      "Spacious and feature-rich cabin",
      "OMEGA platform architecture",
      "Advanced safety features",
      "Strong build quality",
    ],
    specifications: {
      engine: "2.0L Turbo Diesel",
      displacement: "1956 cc",
      maxPower: "170 PS @ 3750 rpm",
      maxTorque: "350 Nm @ 1750-2500 rpm",
      fuelTankCapacity: "50 L",
      bootSpace: "425 L",
      seatingCapacity: 5,
      groundClearance: "205 mm",
      length: "4598 mm",
      width: "1894 mm",
      height: "1706 mm",
      wheelbase: "2741 mm",
      kerbWeight: "1675 kg",
      gearbox: "6-speed Manual / 6-speed Automatic",
      driveType: "FWD",
      suspensionFront: "MacPherson Strut",
      suspensionRear: "Multilink",
      brakeFront: "Disc",
      brakeRear: "Disc",
      wheelSize: "17 inch",
      tyreSize: "235/65 R17",
    },
    safety: {
      airbags: "6 Airbags",
      abs: true,
      ebd: true,
      esp: true,
      hillAssist: true,
      tractionControl: true,
      isofix: true,
      reverseCamera: true,
      parkingSensors: "Front & Rear",
      ncapRating: "4 Star",
    },
    features: {
      airConditioning: "Automatic Climate Control",
      powerSteering: true,
      powerWindows: "Front & Rear",
      centralLocking: true,
      keylessEntry: true,
      pushButtonStart: true,
      cruiseControl: true,
      musicSystem: "JBL Premium Audio",
      bluetooth: true,
      usb: true,
      aux: true,
      steeringMountedControls: true,
      touchscreenSize: "8.8 inch",
      navigation: true,
      androidAuto: true,
      appleCarPlay: true,
      wirelessCharging: false,
      sunroof: "Panoramic Sunroof",
      alloyWheels: true,
      fogLamps: true,
      drl: true,
      ledHeadlights: true,
      ledTaillights: true,
      electricOrvm: true,
      rainSensingWipers: true,
      rearWiper: true,
      rearDefogger: true,
    },
    variants: [
      { name: "XE", price: 14.69, fuelType: "Diesel", transmission: "Manual", mileage: "16.35 kmpl", available: true },
      { name: "XM", price: 16.25, fuelType: "Diesel", transmission: "Manual", mileage: "16.35 kmpl", available: true },
      { name: "XT", price: 17.85, fuelType: "Diesel", transmission: "Manual", mileage: "16.35 kmpl", available: true },
      { name: "XZ", price: 19.45, fuelType: "Diesel", transmission: "Manual", mileage: "16.35 kmpl", available: true },
      {
        name: "XZA",
        price: 20.95,
        fuelType: "Diesel",
        transmission: "Automatic",
        mileage: "14.63 kmpl",
        available: true,
      },
      {
        name: "XZ+",
        price: 22.69,
        fuelType: "Diesel",
        transmission: "Automatic",
        mileage: "14.63 kmpl",
        available: true,
      },
    ],
    competitors: [5, 18],
    keywords: ["harrier", "tata", "premium suv", "diesel", "automatic", "panoramic sunroof", "omega platform"],
    isPopular: true,
    isUpcoming: false,
    isElectric: false,
    segment: "Mid-Size SUV",
  },
  {
    id: 9,
    name: "Tata Altroz",
    brand: "Tata",
    model: "Altroz",
    slug: "tata-altroz",
    launchYear: 2020,
    bodyType: "Hatchback",
    priceRange: { min: 6.6, max: 10.74 },
    priceDisplay: "₹6.60 - 10.74 Lakh",
    image: "/placeholder.svg?height=200&width=300",
    images: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    rating: 4.0,
    reviews: 780,
    overview:
      "The Tata Altroz is a premium hatchback built on the ALFA platform. It offers excellent safety, premium interiors, and multiple engine options including a turbo-petrol variant.",
    keyHighlights: [
      "5-star Global NCAP safety rating",
      "Premium build quality",
      "ALFA platform architecture",
      "Turbo-petrol engine option",
      "Spacious interiors",
    ],
    specifications: {
      engine: "1.2L Petrol / 1.2L Turbo Petrol / 1.5L Diesel",
      displacement: "1199 cc / 1199 cc / 1497 cc",
      maxPower: "86 PS / 110 PS / 90 PS",
      maxTorque: "113 Nm / 140 Nm / 200 Nm",
      fuelTankCapacity: "37 L",
      bootSpace: "345 L",
      seatingCapacity: 5,
      groundClearance: "165 mm",
      length: "3990 mm",
      width: "1755 mm",
      height: "1523 mm",
      wheelbase: "2501 mm",
      kerbWeight: "1080 kg",
      gearbox: "5-speed Manual / 6-speed Manual",
      driveType: "FWD",
      suspensionFront: "MacPherson Strut",
      suspensionRear: "Twist Beam",
      brakeFront: "Disc",
      brakeRear: "Drum",
      wheelSize: "16 inch",
      tyreSize: "195/55 R16",
    },
    safety: {
      airbags: "2 Airbags",
      abs: true,
      ebd: true,
      esp: false,
      hillAssist: false,
      tractionControl: false,
      isofix: true,
      reverseCamera: false,
      parkingSensors: "Rear",
      ncapRating: "5 Star",
    },
    features: {
      airConditioning: "Automatic Climate Control",
      powerSteering: true,
      powerWindows: "Front & Rear",
      centralLocking: true,
      keylessEntry: true,
      pushButtonStart: true,
      cruiseControl: false,
      musicSystem: "Harman ConnectNext",
      bluetooth: true,
      usb: true,
      aux: true,
      steeringMountedControls: true,
      touchscreenSize: "7 inch",
      navigation: false,
      androidAuto: true,
      appleCarPlay: true,
      wirelessCharging: false,
      alloyWheels: true,
      fogLamps: true,
      drl: true,
      ledHeadlights: false,
      ledTaillights: true,
      electricOrvm: true,
      rainSensingWipers: false,
      rearWiper: true,
      rearDefogger: true,
    },
    variants: [
      { name: "XE", price: 6.6, fuelType: "Petrol", transmission: "Manual", mileage: "25.11 kmpl", available: true },
      { name: "XM", price: 7.55, fuelType: "Petrol", transmission: "Manual", mileage: "25.11 kmpl", available: true },
      { name: "XT", price: 8.9, fuelType: "Petrol", transmission: "Manual", mileage: "25.11 kmpl", available: true },
      { name: "XZ", price: 9.55, fuelType: "Petrol", transmission: "Manual", mileage: "25.11 kmpl", available: true },
      {
        name: "iTurbo",
        price: 10.74,
        fuelType: "Petrol",
        transmission: "Manual",
        mileage: "18.13 kmpl",
        available: true,
      },
    ],
    competitors: [1, 2, 5],
    keywords: ["altroz", "tata", "premium hatchback", "petrol", "turbo", "diesel", "5 star safety", "alfa platform"],
    isPopular: true,
    isUpcoming: false,
    isElectric: false,
    segment: "B2-Hatchback",
  },

  // HONDA CARS
  {
    id: 10,
    name: "Honda City",
    brand: "Honda",
    model: "City",
    slug: "honda-city",
    launchYear: 2020,
    bodyType: "Sedan",
    priceRange: { min: 11.82, max: 16.35 },
    priceDisplay: "₹11.82 - 16.35 Lakh",
    image: "/placeholder.svg?height=200&width=300",
    images: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    rating: 4.3,
    reviews: 750,
    overview:
      "The Honda City is a premium sedan that offers excellent build quality, spacious interiors, and refined driving experience. It's known for its reliability and strong resale value.",
    keyHighlights: [
      "Premium build quality",
      "Spacious and comfortable interiors",
      "Refined driving experience",
      "Strong resale value",
      "Advanced safety features",
    ],
    specifications: {
      engine: "1.5L i-VTEC Petrol / 1.5L i-DTEC Diesel",
      displacement: "1498 cc / 1498 cc",
      maxPower: "121 PS / 100 PS",
      maxTorque: "145 Nm / 200 Nm",
      fuelTankCapacity: "40 L",
      bootSpace: "506 L",
      seatingCapacity: 5,
      groundClearance: "165 mm",
      length: "4549 mm",
      width: "1748 mm",
      height: "1489 mm",
      wheelbase: "2600 mm",
      kerbWeight: "1135 kg",
      gearbox: "6-speed Manual / CVT",
      driveType: "FWD",
      suspensionFront: "MacPherson Strut",
      suspensionRear: "Torsion Beam",
      brakeFront: "Disc",
      brakeRear: "Drum",
      wheelSize: "16 inch",
      tyreSize: "185/55 R16",
    },
    safety: {
      airbags: "6 Airbags",
      abs: true,
      ebd: true,
      esp: true,
      hillAssist: true,
      tractionControl: true,
      isofix: true,
      reverseCamera: true,
      parkingSensors: "Rear",
      ncapRating: "5 Star",
    },
    features: {
      airConditioning: "Automatic Climate Control",
      powerSteering: true,
      powerWindows: "Front & Rear",
      centralLocking: true,
      keylessEntry: true,
      pushButtonStart: true,
      cruiseControl: true,
      musicSystem: "Honda Connect",
      bluetooth: true,
      usb: true,
      aux: true,
      steeringMountedControls: true,
      touchscreenSize: "8 inch",
      navigation: true,
      androidAuto: true,
      appleCarPlay: true,
      wirelessCharging: false,
      sunroof: "Electric Sunroof",
      alloyWheels: true,
      fogLamps: true,
      drl: true,
      ledHeadlights: true,
      ledTaillights: true,
      electricOrvm: true,
      rainSensingWipers: true,
      rearWiper: false,
      rearDefogger: true,
    },
    variants: [
      { name: "SV", price: 11.82, fuelType: "Petrol", transmission: "Manual", mileage: "17.8 kmpl", available: true },
      { name: "V", price: 13.32, fuelType: "Petrol", transmission: "Manual", mileage: "17.8 kmpl", available: true },
      { name: "VX", price: 14.67, fuelType: "Petrol", transmission: "CVT", mileage: "18.4 kmpl", available: true },
      { name: "ZX", price: 16.35, fuelType: "Petrol", transmission: "CVT", mileage: "18.4 kmpl", available: true },
    ],
    competitors: [3, 12],
    keywords: ["city", "honda", "sedan", "premium sedan", "petrol", "cvt", "sunroof", "reliable"],
    isPopular: true,
    isUpcoming: false,
    isElectric: false,
    segment: "C-Sedan",
  },
  {
    id: 11,
    name: "Honda Amaze",
    brand: "Honda",
    model: "Amaze",
    slug: "honda-amaze",
    launchYear: 2018,
    bodyType: "Sedan",
    priceRange: { min: 6.32, max: 9.96 },
    priceDisplay: "₹6.32 - 9.96 Lakh",
    image: "/placeholder.svg?height=200&width=300",
    images: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    rating: 4.0,
    reviews: 650,
    overview:
      "The Honda Amaze is a compact sedan that offers Honda's reliability and build quality at an affordable price. It provides good space utilization and fuel efficiency.",
    keyHighlights: [
      "Honda reliability and build quality",
      "Good space utilization",
      "Fuel efficient engines",
      "Affordable pricing",
      "CVT transmission option",
    ],
    specifications: {
      engine: "1.2L i-VTEC Petrol / 1.5L i-DTEC Diesel",
      displacement: "1199 cc / 1498 cc",
      maxPower: "90 PS / 100 PS",
      maxTorque: "110 Nm / 200 Nm",
      fuelTankCapacity: "35 L",
      bootSpace: "420 L",
      seatingCapacity: 5,
      groundClearance: "165 mm",
      length: "3995 mm",
      width: "1695 mm",
      height: "1501 mm",
      wheelbase: "2470 mm",
      kerbWeight: "1000 kg",
      gearbox: "5-speed Manual / CVT",
      driveType: "FWD",
      suspensionFront: "MacPherson Strut",
      suspensionRear: "Torsion Beam",
      brakeFront: "Disc",
      brakeRear: "Drum",
      wheelSize: "15 inch",
      tyreSize: "175/65 R15",
    },
    safety: {
      airbags: "2 Airbags",
      abs: true,
      ebd: true,
      esp: false,
      hillAssist: false,
      tractionControl: false,
      isofix: true,
      reverseCamera: false,
      parkingSensors: "Rear",
      ncapRating: "3 Star",
    },
    features: {
      airConditioning: "Manual AC",
      powerSteering: true,
      powerWindows: "Front & Rear",
      centralLocking: true,
      keylessEntry: false,
      pushButtonStart: false,
      cruiseControl: false,
      musicSystem: "Honda Connect",
      bluetooth: true,
      usb: true,
      aux: true,
      steeringMountedControls: true,
      touchscreenSize: "7 inch",
      navigation: false,
      androidAuto: true,
      appleCarPlay: true,
      wirelessCharging: false,
      alloyWheels: true,
      fogLamps: true,
      drl: false,
      ledHeadlights: false,
      ledTaillights: false,
      electricOrvm: true,
      rainSensingWipers: false,
      rearWiper: false,
      rearDefogger: true,
    },
    variants: [
      { name: "E", price: 6.32, fuelType: "Petrol", transmission: "Manual", mileage: "18.3 kmpl", available: true },
      { name: "S", price: 7.32, fuelType: "Petrol", transmission: "Manual", mileage: "18.3 kmpl", available: true },
      { name: "S CVT", price: 8.32, fuelType: "Petrol", transmission: "CVT", mileage: "19.0 kmpl", available: true },
      { name: "VX", price: 9.96, fuelType: "Petrol", transmission: "CVT", mileage: "19.0 kmpl", available: true },
    ],
    competitors: [3],
    keywords: ["amaze", "honda", "compact sedan", "petrol", "diesel", "cvt", "affordable", "reliable"],
    isPopular: true,
    isUpcoming: false,
    isElectric: false,
    segment: "B-Sedan",
  },
  {
    id: 12,
    name: "Honda Jazz",
    brand: "Honda",
    model: "Jazz",
    slug: "honda-jazz",
    launchYear: 2015,
    bodyType: "Hatchback",
    priceRange: { min: 7.99, max: 10.87 },
    priceDisplay: "₹7.99 - 10.87 Lakh",
    image: "/placeholder.svg?height=200&width=300",
    images: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    rating: 4.0,
    reviews: 420,
    overview:
      "The Honda Jazz is a premium hatchback known for its spacious interiors, versatile seating, and Honda's renowned build quality. It offers excellent space utilization with its Magic Seats.",
    keyHighlights: [
      "Magic Seats for versatile space",
      "Spacious and premium interiors",
      "Honda build quality",
      "CVT transmission",
      "Good fuel efficiency",
    ],
    specifications: {
      engine: "1.2L i-VTEC Petrol",
      displacement: "1199 cc",
      maxPower: "90 PS @ 6000 rpm",
      maxTorque: "110 Nm @ 4800 rpm",
      fuelTankCapacity: "40 L",
      bootSpace: "354 L",
      seatingCapacity: 5,
      groundClearance: "165 mm",
      length: "3995 mm",
      width: "1694 mm",
      height: "1544 mm",
      wheelbase: "2530 mm",
      kerbWeight: "1050 kg",
      gearbox: "5-speed Manual / CVT",
      driveType: "FWD",
      suspensionFront: "MacPherson Strut",
      suspensionRear: "Torsion Beam",
      brakeFront: "Disc",
      brakeRear: "Drum",
      wheelSize: "15 inch",
      tyreSize: "175/65 R15",
    },
    safety: {
      airbags: "2 Airbags",
      abs: true,
      ebd: true,
      esp: false,
      hillAssist: false,
      tractionControl: false,
      isofix: true,
      reverseCamera: false,
      parkingSensors: "Rear",
      ncapRating: "3 Star",
    },
    features: {
      airConditioning: "Automatic Climate Control",
      powerSteering: true,
      powerWindows: "Front & Rear",
      centralLocking: true,
      keylessEntry: true,
      pushButtonStart: true,
      cruiseControl: false,
      musicSystem: "Honda Connect",
      bluetooth: true,
      usb: true,
      aux: true,
      steeringMountedControls: true,
      touchscreenSize: "7 inch",
      navigation: false,
      androidAuto: true,
      appleCarPlay: true,
      wirelessCharging: false,
      alloyWheels: true,
      fogLamps: true,
      drl: false,
      ledHeadlights: false,
      ledTaillights: false,
      electricOrvm: true,
      rainSensingWipers: false,
      rearWiper: true,
      rearDefogger: true,
    },
    variants: [
      { name: "V", price: 7.99, fuelType: "Petrol", transmission: "Manual", mileage: "17.1 kmpl", available: true },
      { name: "VX", price: 9.22, fuelType: "Petrol", transmission: "Manual", mileage: "17.1 kmpl", available: true },
      { name: "VX CVT", price: 10.87, fuelType: "Petrol", transmission: "CVT", mileage: "16.0 kmpl", available: true },
    ],
    competitors: [1, 2, 5],
    keywords: ["jazz", "honda", "premium hatchback", "petrol", "cvt", "magic seats", "spacious"],
    isPopular: false,
    isUpcoming: false,
    isElectric: false,
    segment: "B2-Hatchback",
  },

  // MAHINDRA CARS
  {
    id: 13,
    name: "Mahindra Thar",
    brand: "Mahindra",
    model: "Thar",
    slug: "mahindra-thar",
    launchYear: 2020,
    bodyType: "SUV",
    priceRange: { min: 13.53, max: 16.78 },
    priceDisplay: "₹13.53 - 16.78 Lakh",
    image: "/placeholder.svg?height=200&width=300",
    images: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    rating: 4.6,
    reviews: 890,
    overview:
      "The Mahindra Thar is an iconic off-road SUV that combines rugged capability with modern features. It's designed for adventure enthusiasts who want to explore the unexplored.",
    keyHighlights: [
      "Iconic off-road capability",
      "4x4 drivetrain available",
      "Convertible soft-top option",
      "Modern features and safety",
      "Strong brand heritage",
    ],
    specifications: {
      engine: "2.0L mStallion Petrol / 2.2L mHawk Diesel",
      displacement: "1997 cc / 2184 cc",
      maxPower: "150 PS / 130 PS",
      maxTorque: "300 Nm / 320 Nm",
      fuelTankCapacity: "57 L",
      bootSpace: "N/A",
      seatingCapacity: 4,
      groundClearance: "226 mm",
      length: "3985 mm",
      width: "1855 mm",
      height: "1844 mm",
      wheelbase: "2450 mm",
      kerbWeight: "1855 kg",
      gearbox: "6-speed Manual / 6-speed Automatic",
      driveType: "RWD / 4WD",
      suspensionFront: "Independent Double Wishbone",
      suspensionRear: "Multilink",
      brakeFront: "Disc",
      brakeRear: "Disc",
      wheelSize: "18 inch",
      tyreSize: "245/70 R18",
    },
    safety: {
      airbags: "2 Airbags",
      abs: true,
      ebd: true,
      esp: true,
      hillAssist: true,
      tractionControl: true,
      isofix: false,
      reverseCamera: true,
      parkingSensors: "Rear",
      ncapRating: "4 Star",
    },
    features: {
      airConditioning: "Manual AC",
      powerSteering: true,
      powerWindows: "Front & Rear",
      centralLocking: true,
      keylessEntry: false,
      pushButtonStart: false,
      cruiseControl: false,
      musicSystem: "AdrenoX Connect",
      bluetooth: true,
      usb: true,
      aux: true,
      steeringMountedControls: true,
      touchscreenSize: "7 inch",
      navigation: false,
      androidAuto: true,
      appleCarPlay: true,
      wirelessCharging: false,
      sunroof: "Convertible Soft Top",
      alloyWheels: true,
      fogLamps: true,
      drl: true,
      ledHeadlights: true,
      ledTaillights: true,
      electricOrvm: true,
      rainSensingWipers: false,
      rearWiper: true,
      rearDefogger: false,
    },
    variants: [
      { name: "AX", price: 13.53, fuelType: "Petrol", transmission: "Manual", mileage: "15.2 kmpl", available: true },
      { name: "LX", price: 14.15, fuelType: "Petrol", transmission: "Manual", mileage: "15.2 kmpl", available: true },
      {
        name: "LX AT",
        price: 15.49,
        fuelType: "Petrol",
        transmission: "Automatic",
        mileage: "15.2 kmpl",
        available: true,
      },
      {
        name: "LX Diesel",
        price: 15.49,
        fuelType: "Diesel",
        transmission: "Manual",
        mileage: "15.2 kmpl",
        available: true,
      },
      {
        name: "LX Diesel AT",
        price: 16.78,
        fuelType: "Diesel",
        transmission: "Automatic",
        mileage: "15.2 kmpl",
        available: true,
      },
    ],
    competitors: [17, 18],
    keywords: ["thar", "mahindra", "off-road", "suv", "4x4", "petrol", "diesel", "convertible", "adventure"],
    isPopular: true,
    isUpcoming: false,
    isElectric: false,
    segment: "Mid-Size SUV",
  },
  {
    id: 14,
    name: "Mahindra XUV700",
    brand: "Mahindra",
    model: "XUV700",
    slug: "mahindra-xuv700",
    launchYear: 2021,
    bodyType: "SUV",
    priceRange: { min: 13.45, max: 25.15 },
    priceDisplay: "₹13.45 - 25.15 Lakh",
    image: "/placeholder.svg?height=200&width=300",
    images: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    rating: 4.5,
    reviews: 650,
    overview:
      "The Mahindra XUV700 is a premium SUV that offers cutting-edge technology, powerful engines, and advanced safety features. It represents Mahindra's flagship offering in the SUV segment.",
    keyHighlights: [
      "Advanced driver assistance systems",
      "Powerful turbo engines",
      "Premium interiors and features",
      "7-seater configuration available",
      "All-wheel drive option",
    ],
    specifications: {
      engine: "2.0L mStallion Petrol / 2.2L mHawk Diesel",
      displacement: "1997 cc / 2184 cc",
      maxPower: "200 PS / 185 PS",
      maxTorque: "380 Nm / 420 Nm",
      fuelTankCapacity: "60 L",
      bootSpace: "408 L",
      seatingCapacity: 7,
      groundClearance: "200 mm",
      length: "4695 mm",
      width: "1890 mm",
      height: "1755 mm",
      wheelbase: "2750 mm",
      kerbWeight: "1993 kg",
      gearbox: "6-speed Manual / 6-speed Automatic",
      driveType: "FWD / AWD",
      suspensionFront: "Independent MacPherson Strut",
      suspensionRear: "Multilink",
      brakeFront: "Disc",
      brakeRear: "Disc",
      wheelSize: "18 inch",
      tyreSize: "235/60 R18",
    },
    safety: {
      airbags: "7 Airbags",
      abs: true,
      ebd: true,
      esp: true,
      hillAssist: true,
      tractionControl: true,
      isofix: true,
      reverseCamera: true,
      parkingSensors: "Front & Rear",
      ncapRating: "5 Star",
    },
    features: {
      airConditioning: "Dual Zone Climate Control",
      powerSteering: true,
      powerWindows: "Front & Rear",
      centralLocking: true,
      keylessEntry: true,
      pushButtonStart: true,
      cruiseControl: true,
      musicSystem: "AdrenoX Connect",
      bluetooth: true,
      usb: true,
      aux: true,
      steeringMountedControls: true,
      touchscreenSize: "10.25 inch",
      navigation: true,
      androidAuto: true,
      appleCarPlay: true,
      wirelessCharging: true,
      sunroof: "Panoramic Sunroof",
      alloyWheels: true,
      fogLamps: true,
      drl: true,
      ledHeadlights: true,
      ledTaillights: true,
      electricOrvm: true,
      rainSensingWipers: true,
      rearWiper: true,
      rearDefogger: true,
    },
    variants: [
      { name: "MX", price: 13.45, fuelType: "Petrol", transmission: "Manual", mileage: "13 kmpl", available: true },
      { name: "AX3", price: 15.49, fuelType: "Petrol", transmission: "Manual", mileage: "13 kmpl", available: true },
      { name: "AX5", price: 17.99, fuelType: "Petrol", transmission: "Manual", mileage: "13 kmpl", available: true },
      {
        name: "AX7",
        price: 20.99,
        fuelType: "Petrol",
        transmission: "Automatic",
        mileage: "12.1 kmpl",
        available: true,
      },
      {
        name: "AX7 L",
        price: 25.15,
        fuelType: "Petrol",
        transmission: "Automatic",
        mileage: "12.1 kmpl",
        available: true,
      },
    ],
    competitors: [4, 8, 18],
    keywords: ["xuv700", "mahindra", "premium suv", "petrol", "diesel", "automatic", "awd", "7 seater", "adas"],
    isPopular: true,
    isUpcoming: false,
    isElectric: false,
    segment: "Mid-Size SUV",
  },
  {
    id: 15,
    name: "Mahindra Scorpio",
    brand: "Mahindra",
    model: "Scorpio",
    slug: "mahindra-scorpio",
    launchYear: 2022,
    bodyType: "SUV",
    priceRange: { min: 13.62, max: 17.42 },
    priceDisplay: "₹13.62 - 17.42 Lakh",
    image: "/placeholder.svg?height=200&width=300",
    images: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    rating: 4.1,
    reviews: 920,
    overview:
      "The Mahindra Scorpio is a rugged SUV that has been a favorite among Indian families for decades. The new generation offers modern features while retaining its tough and reliable character.",
    keyHighlights: [
      "Proven rugged reliability",
      "Spacious 7-seater configuration",
      "Strong diesel engine",
      "Good ground clearance",
      "Value for money proposition",
    ],
    specifications: {
      engine: "2.2L mHawk Diesel",
      displacement: "2184 cc",
      maxPower: "130 PS @ 3750 rpm",
      maxTorque: "300 Nm @ 1750-2800 rpm",
      fuelTankCapacity: "57 L",
      bootSpace: "203 L",
      seatingCapacity: 7,
      groundClearance: "180 mm",
      length: "4662 mm",
      width: "1847 mm",
      height: "1857 mm",
      wheelbase: "2680 mm",
      kerbWeight: "1795 kg",
      gearbox: "6-speed Manual / 6-speed Automatic",
      driveType: "RWD",
      suspensionFront: "Independent Double Wishbone",
      suspensionRear: "Multilink",
      brakeFront: "Disc",
      brakeRear: "Disc",
      wheelSize: "17 inch",
      tyreSize: "235/65 R17",
    },
    safety: {
      airbags: "6 Airbags",
      abs: true,
      ebd: true,
      esp: true,
      hillAssist: true,
      tractionControl: true,
      isofix: true,
      reverseCamera: true,
      parkingSensors: "Front & Rear",
      ncapRating: "3 Star",
    },
    features: {
      airConditioning: "Manual AC",
      powerSteering: true,
      powerWindows: "Front & Rear",
      centralLocking: true,
      keylessEntry: false,
      pushButtonStart: false,
      cruiseControl: false,
      musicSystem: "AdrenoX Connect",
      bluetooth: true,
      usb: true,
      aux: true,
      steeringMountedControls: true,
      touchscreenSize: "9 inch",
      navigation: false,
      androidAuto: true,
      appleCarPlay: true,
      wirelessCharging: false,
      alloyWheels: true,
      fogLamps: true,
      drl: true,
      ledHeadlights: false,
      ledTaillights: true,
      electricOrvm: true,
      rainSensingWipers: false,
      rearWiper: true,
      rearDefogger: true,
    },
    variants: [
      { name: "S3", price: 13.62, fuelType: "Diesel", transmission: "Manual", mileage: "15.4 kmpl", available: true },
      { name: "S5", price: 14.99, fuelType: "Diesel", transmission: "Manual", mileage: "15.4 kmpl", available: true },
      { name: "S7", price: 15.99, fuelType: "Diesel", transmission: "Manual", mileage: "15.4 kmpl", available: true },
      { name: "S9", price: 16.99, fuelType: "Diesel", transmission: "Manual", mileage: "15.4 kmpl", available: true },
      {
        name: "S11",
        price: 17.42,
        fuelType: "Diesel",
        transmission: "Automatic",
        mileage: "14.4 kmpl",
        available: true,
      },
    ],
    competitors: [13, 14, 18],
    keywords: ["scorpio", "mahindra", "suv", "diesel", "7 seater", "rugged", "reliable", "family suv"],
    isPopular: true,
    isUpcoming: false,
    isElectric: false,
    segment: "Mid-Size SUV",
  },

  // TOYOTA CARS
  {
    id: 16,
    name: "Toyota Innova Crysta",
    brand: "Toyota",
    model: "Innova Crysta",
    slug: "toyota-innova-crysta",
    launchYear: 2016,
    bodyType: "MUV",
    priceRange: { min: 17.86, max: 26.55 },
    priceDisplay: "₹17.86 - 26.55 Lakh",
    image: "/placeholder.svg?height=200&width=300",
    images: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    rating: 4.4,
    reviews: 420,
    overview:
      "The Toyota Innova Crysta is the benchmark for premium MPVs in India. Known for its reliability, comfort, and spacious interiors, it's the preferred choice for families and commercial use.",
    keyHighlights: [
      "Legendary Toyota reliability",
      "Spacious and comfortable interiors",
      "Strong resale value",
      "Excellent ride quality",
      "Premium build quality",
    ],
    specifications: {
      engine: "2.7L Petrol / 2.4L Diesel",
      displacement: "2694 cc / 2393 cc",
      maxPower: "166 PS / 150 PS",
      maxTorque: "245 Nm / 343 Nm",
      fuelTankCapacity: "65 L",
      bootSpace: "300 L",
      seatingCapacity: 8,
      groundClearance: "178 mm",
      length: "4735 mm",
      width: "1830 mm",
      height: "1795 mm",
      wheelbase: "2750 mm",
      kerbWeight: "1695 kg",
      gearbox: "5-speed Manual / 6-speed Automatic",
      driveType: "RWD",
      suspensionFront: "Double Wishbone",
      suspensionRear: "4-Link with Lateral Rod",
      brakeFront: "Disc",
      brakeRear: "Disc",
      wheelSize: "17 inch",
      tyreSize: "215/55 R17",
    },
    safety: {
      airbags: "3 Airbags",
      abs: true,
      ebd: true,
      esp: true,
      hillAssist: true,
      tractionControl: true,
      isofix: true,
      reverseCamera: true,
      parkingSensors: "Front & Rear",
      ncapRating: "4 Star",
    },
    features: {
      airConditioning: "Dual Zone Climate Control",
      powerSteering: true,
      powerWindows: "Front & Rear",
      centralLocking: true,
      keylessEntry: true,
      pushButtonStart: true,
      cruiseControl: true,
      musicSystem: "Toyota Smart Playcast",
      bluetooth: true,
      usb: true,
      aux: true,
      steeringMountedControls: true,
      touchscreenSize: "9 inch",
      navigation: true,
      androidAuto: true,
      appleCarPlay: true,
      wirelessCharging: false,
      alloyWheels: true,
      fogLamps: true,
      drl: true,
      ledHeadlights: true,
      ledTaillights: true,
      electricOrvm: true,
      rainSensingWipers: false,
      rearWiper: true,
      rearDefogger: true,
    },
    variants: [
      { name: "GX", price: 17.86, fuelType: "Petrol", transmission: "Manual", mileage: "11.25 kmpl", available: true },
      {
        name: "VX",
        price: 21.99,
        fuelType: "Petrol",
        transmission: "Automatic",
        mileage: "10.75 kmpl",
        available: true,
      },
      {
        name: "ZX",
        price: 26.55,
        fuelType: "Diesel",
        transmission: "Automatic",
        mileage: "15.6 kmpl",
        available: true,
      },
    ],
    competitors: [14, 15],
    keywords: ["innova", "crysta", "toyota", "mpv", "muv", "petrol", "diesel", "8 seater", "reliable", "premium"],
    isPopular: true,
    isUpcoming: false,
    isElectric: false,
    segment: "Premium MPV",
  },
  {
    id: 17,
    name: "Toyota Fortuner",
    brand: "Toyota",
    model: "Fortuner",
    slug: "toyota-fortuner",
    launchYear: 2016,
    bodyType: "SUV",
    priceRange: { min: 32.59, max: 50.34 },
    priceDisplay: "₹32.59 - 50.34 Lakh",
    image: "/placeholder.svg?height=200&width=300",
    images: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    rating: 4.5,
    reviews: 340,
    overview:
      "The Toyota Fortuner is a premium SUV that offers commanding road presence, excellent off-road capability, and legendary Toyota reliability. It's the choice for those who want a premium SUV experience.",
    keyHighlights: [
      "Premium SUV with commanding presence",
      "Excellent off-road capability",
      "Toyota reliability and build quality",
      "4x4 drivetrain available",
      "Strong resale value",
    ],
    specifications: {
      engine: "2.7L Petrol / 2.8L Diesel",
      displacement: "2694 cc / 2755 cc",
      maxPower: "166 PS / 204 PS",
      maxTorque: "245 Nm / 500 Nm",
      fuelTankCapacity: "80 L",
      bootSpace: "296 L",
      seatingCapacity: 7,
      groundClearance: "225 mm",
      length: "4795 mm",
      width: "1855 mm",
      height: "1835 mm",
      wheelbase: "2745 mm",
      kerbWeight: "2140 kg",
      gearbox: "6-speed Manual / 6-speed Automatic",
      driveType: "RWD / 4WD",
      suspensionFront: "Double Wishbone",
      suspensionRear: "4-Link with Coil Spring",
      brakeFront: "Disc",
      brakeRear: "Disc",
      wheelSize: "18 inch",
      tyreSize: "265/60 R18",
    },
    safety: {
      airbags: "7 Airbags",
      abs: true,
      ebd: true,
      esp: true,
      hillAssist: true,
      tractionControl: true,
      isofix: true,
      reverseCamera: true,
      parkingSensors: "Front & Rear",
      ncapRating: "5 Star",
    },
    features: {
      airConditioning: "Dual Zone Climate Control",
      powerSteering: true,
      powerWindows: "Front & Rear",
      centralLocking: true,
      keylessEntry: true,
      pushButtonStart: true,
      cruiseControl: true,
      musicSystem: "Toyota Smart Playcast",
      bluetooth: true,
      usb: true,
      aux: true,
      steeringMountedControls: true,
      touchscreenSize: "9 inch",
      navigation: true,
      androidAuto: true,
      appleCarPlay: true,
      wirelessCharging: true,
      alloyWheels: true,
      fogLamps: true,
      drl: true,
      ledHeadlights: true,
      ledTaillights: true,
      electricOrvm: true,
      rainSensingWipers: true,
      rearWiper: true,
      rearDefogger: true,
    },
    variants: [
      {
        name: "4x2 MT",
        price: 32.59,
        fuelType: "Diesel",
        transmission: "Manual",
        mileage: "14.4 kmpl",
        available: true,
      },
      {
        name: "4x2 AT",
        price: 35.99,
        fuelType: "Diesel",
        transmission: "Automatic",
        mileage: "14.2 kmpl",
        available: true,
      },
      {
        name: "4x4 MT",
        price: 37.58,
        fuelType: "Diesel",
        transmission: "Manual",
        mileage: "14.4 kmpl",
        available: true,
      },
      {
        name: "4x4 AT",
        price: 42.33,
        fuelType: "Diesel",
        transmission: "Automatic",
        mileage: "14.2 kmpl",
        available: true,
      },
      {
        name: "Legender 4x4",
        price: 50.34,
        fuelType: "Diesel",
        transmission: "Automatic",
        mileage: "14.2 kmpl",
        available: true,
      },
    ],
    competitors: [13, 14, 15],
    keywords: ["fortuner", "toyota", "premium suv", "diesel", "4x4", "automatic", "off-road", "7 seater"],
    isPopular: true,
    isUpcoming: false,
    isElectric: false,
    segment: "Premium SUV",
  },

  // KIA CARS
  {
    id: 18,
    name: "Kia Seltos",
    brand: "Kia",
    model: "Seltos",
    slug: "kia-seltos",
    launchYear: 2019,
    bodyType: "SUV",
    priceRange: { min: 10.9, max: 18.45 },
    priceDisplay: "₹10.90 - 18.45 Lakh",
    image: "/placeholder.svg?height=200&width=300",
    images: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    rating: 4.3,
    reviews: 720,
    overview:
      "The Kia Seltos is a feature-rich compact SUV that offers bold design, advanced technology, and multiple engine options. It has quickly become a popular choice in the competitive compact SUV segment.",
    keyHighlights: [
      "Bold and distinctive design",
      "Feature-rich cabin with UVO Connect",
      "Multiple engine and transmission options",
      "Good build quality",
      "Comprehensive warranty",
    ],
    specifications: {
      engine: "1.5L Petrol / 1.4L Turbo Petrol / 1.5L Diesel",
      displacement: "1497 cc / 1353 cc / 1493 cc",
      maxPower: "115 PS / 140 PS / 115 PS",
      maxTorque: "144 Nm / 242 Nm / 250 Nm",
      fuelTankCapacity: "50 L",
      bootSpace: "433 L",
      seatingCapacity: 5,
      groundClearance: "190 mm",
      length: "4315 mm",
      width: "1800 mm",
      height: "1645 mm",
      wheelbase: "2610 mm",
      kerbWeight: "1353 kg",
      gearbox: "6-speed Manual / CVT / DCT / Automatic",
      driveType: "FWD",
      suspensionFront: "MacPherson Strut",
      suspensionRear: "Coupled Torsion Beam Axle",
      brakeFront: "Disc",
      brakeRear: "Disc",
      wheelSize: "17 inch",
      tyreSize: "215/60 R17",
    },
    safety: {
      airbags: "6 Airbags",
      abs: true,
      ebd: true,
      esp: true,
      hillAssist: true,
      tractionControl: true,
      isofix: true,
      reverseCamera: true,
      parkingSensors: "Front & Rear",
      ncapRating: "3 Star",
    },
    features: {
      airConditioning: "Automatic Climate Control",
      powerSteering: true,
      powerWindows: "Front & Rear",
      centralLocking: true,
      keylessEntry: true,
      pushButtonStart: true,
      cruiseControl: true,
      musicSystem: "UVO Connect",
      bluetooth: true,
      usb: true,
      aux: true,
      steeringMountedControls: true,
      touchscreenSize: "10.25 inch",
      navigation: true,
      androidAuto: true,
      appleCarPlay: true,
      wirelessCharging: true,
      sunroof: "Electric Sunroof",
      alloyWheels: true,
      fogLamps: true,
      drl: true,
      ledHeadlights: true,
      ledTaillights: true,
      electricOrvm: true,
      rainSensingWipers: true,
      rearWiper: true,
      rearDefogger: true,
    },
    variants: [
      { name: "HTE", price: 10.9, fuelType: "Petrol", transmission: "Manual", mileage: "16.8 kmpl", available: true },
      { name: "HTK", price: 12.4, fuelType: "Petrol", transmission: "Manual", mileage: "16.8 kmpl", available: true },
      { name: "HTX", price: 14.65, fuelType: "Petrol", transmission: "CVT", mileage: "16.1 kmpl", available: true },
      { name: "GTX", price: 16.99, fuelType: "Petrol", transmission: "DCT", mileage: "16.5 kmpl", available: true },
      { name: "X Line", price: 18.45, fuelType: "Petrol", transmission: "DCT", mileage: "16.5 kmpl", available: true },
    ],
    competitors: [4, 7, 6],
    keywords: ["seltos", "kia", "compact suv", "petrol", "turbo", "diesel", "uvo connect", "sunroof", "features"],
    isPopular: true,
    isUpcoming: false,
    isElectric: false,
    segment: "Compact SUV",
  },
  {
    id: 19,
    name: "Kia Sonet",
    brand: "Kia",
    model: "Sonet",
    slug: "kia-sonet",
    launchYear: 2020,
    bodyType: "SUV",
    priceRange: { min: 7.15, max: 13.99 },
    priceDisplay: "₹7.15 - 13.99 Lakh",
    image: "/placeholder.svg?height=200&width=300",
    images: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    rating: 4.2,
    reviews: 580,
    overview:
      "The Kia Sonet is a compact SUV that offers a perfect blend of style, features, and performance. With its bold design and feature-rich cabin, it competes strongly in the sub-compact SUV segment.",
    keyHighlights: [
      "Bold and youthful design",
      "Feature-loaded cabin",
      "Multiple engine options",
      "UVO Connect technology",
      "Good build quality",
    ],
    specifications: {
      engine: "1.2L Petrol / 1.0L Turbo Petrol / 1.5L Diesel",
      displacement: "1197 cc / 998 cc / 1493 cc",
      maxPower: "83 PS / 120 PS / 100 PS",
      maxTorque: "113 Nm / 172 Nm / 240 Nm",
      fuelTankCapacity: "45 L",
      bootSpace: "392 L",
      seatingCapacity: 5,
      groundClearance: "205 mm",
      length: "3995 mm",
      width: "1790 mm",
      height: "1642 mm",
      wheelbase: "2500 mm",
      kerbWeight: "1200 kg",
      gearbox: "5-speed Manual / CVT / DCT / 6-speed Manual",
      driveType: "FWD",
      suspensionFront: "MacPherson Strut",
      suspensionRear: "Coupled Torsion Beam Axle",
      brakeFront: "Disc",
      brakeRear: "Drum",
      wheelSize: "16 inch",
      tyreSize: "205/60 R16",
    },
    safety: {
      airbags: "6 Airbags",
      abs: true,
      ebd: true,
      esp: true,
      hillAssist: true,
      tractionControl: true,
      isofix: true,
      reverseCamera: true,
      parkingSensors: "Rear",
      ncapRating: "3 Star",
    },
    features: {
      airConditioning: "Automatic Climate Control",
      powerSteering: true,
      powerWindows: "Front & Rear",
      centralLocking: true,
      keylessEntry: true,
      pushButtonStart: true,
      cruiseControl: false,
      musicSystem: "UVO Connect",
      bluetooth: true,
      usb: true,
      aux: true,
      steeringMountedControls: true,
      touchscreenSize: "10.25 inch",
      navigation: true,
      androidAuto: true,
      appleCarPlay: true,
      wirelessCharging: true,
      sunroof: "Electric Sunroof",
      alloyWheels: true,
      fogLamps: true,
      drl: true,
      ledHeadlights: true,
      ledTaillights: true,
      electricOrvm: true,
      rainSensingWipers: false,
      rearWiper: true,
      rearDefogger: true,
    },
    variants: [
      { name: "HTE", price: 7.15, fuelType: "Petrol", transmission: "Manual", mileage: "18.4 kmpl", available: true },
      { name: "HTK", price: 8.89, fuelType: "Petrol", transmission: "Manual", mileage: "18.4 kmpl", available: true },
      { name: "HTX", price: 10.99, fuelType: "Petrol", transmission: "CVT", mileage: "18.3 kmpl", available: true },
      { name: "GTX+", price: 13.99, fuelType: "Petrol", transmission: "DCT", mileage: "18.2 kmpl", available: true },
    ],
    competitors: [6, 7, 15],
    keywords: ["sonet", "kia", "sub-compact suv", "petrol", "turbo", "diesel", "uvo connect", "sunroof"],
    isPopular: true,
    isUpcoming: false,
    isElectric: false,
    segment: "Sub-Compact SUV",
  },

  // VOLKSWAGEN CARS
  {
    id: 20,
    name: "Volkswagen Polo",
    brand: "Volkswagen",
    model: "Polo",
    slug: "volkswagen-polo",
    launchYear: 2019,
    bodyType: "Hatchback",
    priceRange: { min: 6.79, max: 10.99 },
    priceDisplay: "₹6.79 - 10.99 Lakh",
    image: "/placeholder.svg?height=200&width=300",
    images: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    rating: 4.1,
    reviews: 430,
    overview:
      "The Volkswagen Polo is a premium hatchback known for its solid build quality, refined driving experience, and European engineering. It offers a premium feel in the hatchback segment.",
    keyHighlights: [
      "Solid German build quality",
      "Refined driving experience",
      "Premium interiors",
      "Good safety features",
      "Strong road presence",
    ],
    specifications: {
      engine: "1.0L TSI Petrol",
      displacement: "999 cc",
      maxPower: "110 PS @ 5000-5500 rpm",
      maxTorque: "175 Nm @ 1750-4000 rpm",
      fuelTankCapacity: "45 L",
      bootSpace: "294 L",
      seatingCapacity: 5,
      groundClearance: "165 mm",
      length: "3971 mm",
      width: "1682 mm",
      height: "1469 mm",
      wheelbase: "2469 mm",
      kerbWeight: "1070 kg",
      gearbox: "6-speed Manual / 6-speed Automatic",
      driveType: "FWD",
      suspensionFront: "MacPherson Strut",
      suspensionRear: "Torsion Beam",
      brakeFront: "Disc",
      brakeRear: "Drum",
      wheelSize: "15 inch",
      tyreSize: "185/60 R15",
    },
    safety: {
      airbags: "2 Airbags",
      abs: true,
      ebd: true,
      esp: true,
      hillAssist: true,
      tractionControl: true,
      isofix: true,
      reverseCamera: false,
      parkingSensors: "Rear",
      ncapRating: "4 Star",
    },
    features: {
      airConditioning: "Manual AC",
      powerSteering: true,
      powerWindows: "Front & Rear",
      centralLocking: true,
      keylessEntry: false,
      pushButtonStart: false,
      cruiseControl: true,
      musicSystem: "Composition Media",
      bluetooth: true,
      usb: true,
      aux: true,
      steeringMountedControls: true,
      touchscreenSize: "6.5 inch",
      navigation: false,
      androidAuto: true,
      appleCarPlay: true,
      wirelessCharging: false,
      alloyWheels: true,
      fogLamps: true,
      drl: false,
      ledHeadlights: false,
      ledTaillights: false,
      electricOrvm: true,
      rainSensingWipers: true,
      rearWiper: true,
      rearDefogger: true,
    },
    variants: [
      {
        name: "Trendline",
        price: 6.79,
        fuelType: "Petrol",
        transmission: "Manual",
        mileage: "18.24 kmpl",
        available: true,
      },
      {
        name: "Comfortline",
        price: 8.09,
        fuelType: "Petrol",
        transmission: "Manual",
        mileage: "18.24 kmpl",
        available: true,
      },
      {
        name: "Highline",
        price: 9.59,
        fuelType: "Petrol",
        transmission: "Manual",
        mileage: "18.24 kmpl",
        available: true,
      },
      {
        name: "Highline AT",
        price: 10.99,
        fuelType: "Petrol",
        transmission: "Automatic",
        mileage: "16.47 kmpl",
        available: true,
      },
    ],
    competitors: [1, 2, 5],
    keywords: ["polo", "volkswagen", "premium hatchback", "petrol", "tsi", "german", "build quality"],
    isPopular: false,
    isUpcoming: false,
    isElectric: false,
    segment: "B2-Hatchback",
  },

  {
    id: 21,
    name: "Tata Nexon EV",
    brand: "Tata",
    model: "Nexon EV",
    slug: "tata-nexon-ev",
    launchYear: 2023,
    bodyType: "SUV",
    priceRange: { min: 14.49, max: 19.49 },
    priceDisplay: "₹14.49 - 19.49 Lakh",
    image: "/placeholder.svg?height=200&width=300",
    images: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    rating: 4.5,
    reviews: 980,
    overview:
      "The Tata Nexon EV is one of India's best-selling electric SUVs, offering strong performance, long driving range, and modern features with zero emissions.",
    keyHighlights: [
      "Long driving range",
      "Fast charging support",
      "5-star safety rating",
      "Low running cost",
      "Connected car tech",
    ],
    specifications: {
      battery: "40.5 kWh",
      range: "465 km",
      maxPower: "143 PS",
      maxTorque: "215 Nm",
      chargingTime: "6.5 hours (AC) / 56 min (DC fast)",
      bootSpace: "350 L",
      seatingCapacity: 5,
      groundClearance: "190 mm",
      length: "3994 mm",
      width: "1811 mm",
      height: "1616 mm",
      wheelbase: "2498 mm",
      kerbWeight: "1400 kg",
      gearbox: "Automatic",
      driveType: "FWD",
    },
    safety: {
      airbags: "6 Airbags",
      abs: true,
      ebd: true,
      esp: true,
      hillAssist: true,
      tractionControl: true,
      isofix: true,
      reverseCamera: true,
      parkingSensors: "Front & Rear",
      ncapRating: "5 Star",
    },
    features: {
      airConditioning: "Automatic Climate Control",
      powerSteering: true,
      powerWindows: "Front & Rear",
      centralLocking: true,
      keylessEntry: true,
      pushButtonStart: true,
      cruiseControl: true,
      touchscreenSize: "12.3 inch",
      androidAuto: true,
      appleCarPlay: true,
      wirelessCharging: true,
      sunroof: "Electric Sunroof",
      alloyWheels: true,
      ledHeadlights: true,
    },
    variants: [
      {
        name: "Creative",
        price: 14.49,
        fuelType: "Electric",
        transmission: "Automatic",
        mileage: "465 km range",
        available: true,
      },
      {
        name: "Fearless",
        price: 16.49,
        fuelType: "Electric",
        transmission: "Automatic",
        mileage: "465 km range",
        available: true,
      },
    ],
    competitors: [7],
    keywords: ["nexon ev", "tata", "electric suv", "ev", "long range"],
    isPopular: true,
    isUpcoming: false,
    isElectric: true,
    segment: "Electric SUV",
  },
  {
    id: 22,
    name: "MG ZS EV",
    brand: "MG",
    model: "ZS EV",
    slug: "mg-zs-ev",
    launchYear: 2023,
    bodyType: "SUV",
    priceRange: { min: 18.98, max: 25.20 },
    priceDisplay: "₹18.98 - 25.20 Lakh",
    image: "/placeholder.svg?height=200&width=300",
    images: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    rating: 4.4,
    reviews: 620,
    overview:
      "The MG ZS EV is a premium electric SUV offering a long range, premium interiors, and advanced connected technology.",
    keyHighlights: [
      "Premium EV SUV",
      "Long range battery",
      "Panoramic sunroof",
      "Advanced safety tech",
      "Fast charging support",
    ],
    specifications: {
      battery: "50.3 kWh",
      range: "461 km",
      maxPower: "176 PS",
      maxTorque: "280 Nm",
      chargingTime: "8.5 hours (AC) / 60 min (DC)",
      bootSpace: "448 L",
      seatingCapacity: 5,
      groundClearance: "177 mm",
      gearbox: "Automatic",
      driveType: "FWD",
    },
    safety: {
      airbags: "6 Airbags",
      abs: true,
      ebd: true,
      esp: true,
      hillAssist: true,
      tractionControl: true,
      isofix: true,
      reverseCamera: true,
      parkingSensors: "Front & Rear",
      ncapRating: "5 Star",
    },
    features: {
      airConditioning: "Automatic Climate Control",
      touchscreenSize: "10.1 inch",
      androidAuto: true,
      appleCarPlay: true,
      wirelessCharging: true,
      sunroof: "Panoramic Sunroof",
      alloyWheels: true,
      ledHeadlights: true,
    },
    variants: [
      {
        name: "Excite",
        price: 18.98,
        fuelType: "Electric",
        transmission: "Automatic",
        mileage: "461 km range",
        available: true,
      },
      {
        name: "Exclusive",
        price: 25.20,
        fuelType: "Electric",
        transmission: "Automatic",
        mileage: "461 km range",
        available: true,
      },
    ],
    competitors: [21],
    keywords: ["zs ev", "mg", "electric suv", "premium ev"],
    isPopular: true,
    isUpcoming: false,
    isElectric: true,
    segment: "Electric SUV",
  },
  {
    id: 23,
    name: "Tata Tiago EV",
    brand: "Tata",
    model: "Tiago EV",
    slug: "tata-tiago-ev",
    launchYear: 2023,
    bodyType: "Hatchback",
    priceRange: { min: 8.69, max: 12.04 },
    priceDisplay: "₹8.69 - 12.04 Lakh",
    image: "/placeholder.svg?height=200&width=300",
    images: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    rating: 4.3,
    reviews: 540,
    overview:
      "The Tata Tiago EV is India's most affordable electric hatchback offering a practical driving range and low running costs.",
    keyHighlights: [
      "Affordable EV",
      "Compact city car",
      "Low running cost",
      "Multiple battery options",
      "Fast charging support",
    ],
    specifications: {
      battery: "24 kWh",
      range: "315 km",
      maxPower: "74 PS",
      maxTorque: "114 Nm",
      chargingTime: "5.7 hours (AC)",
      bootSpace: "240 L",
      seatingCapacity: 5,
      gearbox: "Automatic",
      driveType: "FWD",
    },
    safety: {
      airbags: "2 Airbags",
      abs: true,
      ebd: true,
      esp: false,
      hillAssist: false,
      tractionControl: false,
      isofix: true,
      reverseCamera: true,
      parkingSensors: "Rear",
      ncapRating: "4 Star",
    },
    features: {
      airConditioning: "Automatic AC",
      touchscreenSize: "7 inch",
      androidAuto: true,
      appleCarPlay: true,
      alloyWheels: true,
    },
    variants: [
      {
        name: "XE",
        price: 8.69,
        fuelType: "Electric",
        transmission: "Automatic",
        mileage: "315 km range",
        available: true,
      },
      {
        name: "XZ+",
        price: 12.04,
        fuelType: "Electric",
        transmission: "Automatic",
        mileage: "315 km range",
        available: true,
      },
    ],
    competitors: [21],
    keywords: ["tiago ev", "tata", "electric hatchback", "budget ev"],
    isPopular: true,
    isUpcoming: false,
    isElectric: true,
    segment: "Electric Hatchback",
  }

]

// Search and filter functions
export function searchCars(query: string): CarData[] {
  if (!query || query.length < 2) return []

  const searchTerm = query.toLowerCase().trim()

  return carsDatabase
    .filter((car) => {
      const nameMatch = car.name.toLowerCase().includes(searchTerm)
      const brandMatch = car.brand.toLowerCase().includes(searchTerm)
      const modelMatch = car.model.toLowerCase().includes(searchTerm)
      const keywordMatch = car.keywords.some(
        (keyword) => keyword.toLowerCase().includes(searchTerm) || searchTerm.includes(keyword.toLowerCase()),
      )

      return nameMatch || brandMatch || modelMatch || keywordMatch
    })
    .slice(0, 5)
}

export function findExactCarMatch(query: string): CarData | null {
  if (!query || query.length < 2) return null

  const searchTerm = query.toLowerCase().trim()

  let exactMatch = carsDatabase.find(
    (car) =>
      car.name.toLowerCase() === searchTerm ||
      car.model.toLowerCase() === searchTerm ||
      `${car.brand.toLowerCase()} ${car.model.toLowerCase()}` === searchTerm,
  )

  if (exactMatch) return exactMatch

  exactMatch = carsDatabase.find((car) => {
    const carFullName = `${car.brand} ${car.model}`.toLowerCase()
    const modelName = car.model.toLowerCase()

    return (
      (modelName.includes(searchTerm) && searchTerm.length >= 3) ||
      (carFullName.includes(searchTerm) && searchTerm.length >= 4) ||
      car.keywords.some((keyword) => keyword.toLowerCase() === searchTerm)
    )
  })

  return exactMatch || null
}

export function getCarsByBrand(brand: string): CarData[] {
  return carsDatabase.filter((car) => car.brand.toLowerCase() === brand.toLowerCase())
}

export function getCarsByBodyType(bodyType: string): CarData[] {
  return carsDatabase.filter((car) => car.bodyType.toLowerCase() === bodyType.toLowerCase())
}

export function getCarsByPriceRange(min: number, max: number): CarData[] {
  return carsDatabase.filter((car) => car.priceRange.min >= min && car.priceRange.max <= max)
}

export function getPopularCars(): CarData[] {
  return carsDatabase.filter((car) => car.isPopular)
}

export function getUpcomingCars(): CarData[] {
  return carsDatabase.filter((car) => car.isUpcoming)
}

export function getElectricCars(): CarData[] {
  return carsDatabase.filter((car) => car.isElectric)
}

export function getCarById(id: number): CarData | undefined {
  return carsDatabase.find((car) => car.id === id)
}


export const getCompetitors = (carId: number): CarData[] => {
  const car = getCarById(carId)
  if (!car) return []

  return (car.competitors || [])
    .map((id) => getCarById(id))
    .filter(Boolean) as CarData[]
}

// Brand list for filters
export const brands = Array.from(new Set(carsDatabase.map((car) => car.brand))).sort()

// Body types for filters
export const bodyTypes = Array.from(new Set(carsDatabase.map((car) => car.bodyType))).sort()

// Fuel types for filters
export const fuelTypes = Array.from(
  new Set(
    carsDatabase.flatMap((car) =>
      (car.variants || []).map((variant) => variant.fuelType)
    )
  )
).sort()
// Transmission types for filters
export const transmissionTypes = Array.from(
  new Set(
    carsDatabase.flatMap((car) =>
      (car.variants || []).map((variant) => variant.transmission)
    )
  )
).sort()

// Segments for filters
export const segments = Array.from(new Set(carsDatabase.map((car) => car.segment))).sort()
